version: '3'
services:
  pg:
    image: 'postgres:10-alpine'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_PASSWORD: mystery
      POSTGRES_USER: root
    volumes:
      - ~/docker-data/pg:/var/lib/postgresql/data
    logging:
      driver: none

  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ../../api:/app
    ports:
      - "3000:3000"
    depends_on:
      - pg
